version: "3.8"

services:
  app:
    image: dzaky8/laravel-img
    restart: unless-stopped
    container_name: laravel_app
    working_dir: /var/www/html
    ports:
    - "8000:80"
    volumes:
    - .:/var/www/html
    environment:
    - APP_ENV=local
    - APP_DEBUG=true
    depends_on:
    - db
#    command: >
#      bash -c "php artisan key:generate &&
#               php artisan config:clear &&
#               apache2-foreground "
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: zack
      MYSQL_PASSWORD: Dzaky1210##
    volumes:
    - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
    - "8080:80"
    depends_on:
    - db
    environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:

